import { useEffect, useState } from "react";
import { useWeb3React } from "@web3-react/core";

import Head from "next/head";

import styles from "../styles/Home.module.css";
import ConnectWallet from "../components/ConnectWallet";
import { injected } from "../injected";

export default function Home() {
  const { account, library, activate, active, deactivate } = useWeb3React();

  const [attempted, setAttempted] = useState(false);
  const [connected, setConnected] = useState(!!account);

  const isConnected = !!account;

  useEffect(() => {
    injected.isAuthorized().then((isAuthorized) => {
      console.log("is authed", isAuthorized);
      if (isAuthorized) {
        activate(injected, undefined, true).catch(() => {
          setAttempted(true);
        });
      } else {
        setAttempted(true);
      }
    });
  }, [activate]);

  useEffect(() => {
    if (!attempted && active) {
      setAttempted(true);
    }
  }, [attempted, active]);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next Dapp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Next JS Dapp</h1>
        {isConnected ? (
          "Connected: " + account
        ) : (
          <ConnectWallet attempted={attempted} />
        )}
      </main>
    </div>
  );
}
